name: BonemealRadius:
main: io.github.toomanybugs1.BonemealRadius.BonemealRadius
version: 0.1

permissions:
	bonemealradius.*:
		description: Gives access to all permissions
		children:
			bonemealradius.use: true
			bonemealradius.commands: true
	bonemealradius.use:
		description: Allows usage of the modified bonemeal radius
		default: op
	bonemealradius.commands:
		description: Gives access to all commands
		default: op